name: Generate GitHub Org Report

on:
  workflow_dispatch: # Allows the workflow to be manually triggered
  schedule:
    - cron: "0 15 * * 1" # Runs every Monday at 7 AM PST (15:00 UTC)

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas openpyxl

    - name: Run the script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub PAT stored as a secret
      run: |
        python gh-report_ghaction.py

    - name: Upload report artifact
      uses: actions/upload-artifact@v3
      with:
        name: alerts-report
        path: '*.xlsx'
